# Generated by Django 5.2.10 on 2026-01-08 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=500)),
                ('author', models.CharField(max_length=50)),
                ('entry_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
